<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- Open Systems Support -->
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
        <title>Open Systems Solutions - Payroll</title>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
		<link type="text/css" href="/payroll-test/css/south-street/jquery-ui-1.7.1.custom.css" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="/payroll-test/css/style.css" media="screen" />
        <script src="js/jquery.js" type="text/javascript"></script>
		<script src="js/submitform.js" type="text/javascript"></script>
		<script type="text/javascript" src="js/jquery-ui-1.7.1.custom.min.js"></script>
	</head>
	<body>
	    <div id="header">
	        <center><img src="images/header.gif" alt="header img" /></center>
	        <div id="logo"></div>
	        <div id="listmenu">
	            <ul>
	                <li><a href="http://webmail.rutgers.edu/">Webmail</a></li>
	                <li><a href="http://mailman.rutgers.edu/">Mailman</a></li>
	                <li><a href="https://rams.rutgers.edu/">RAMS</a></li>
	                <li><a href="#">More...</a>
	                <!-- note the proper way to make nested menus w/xhtml...nested list inside of <li> </li> -->
	                    <ul>
	                        <li><a href="https://rats.rutgers.edu">RATS</a></li>
	                        <li><a href="https://rim.rutgers.edu/jwchat/">RIM</a></li>
	                    </ul>
	                </li>
	            </ul>
	        </div>
	        <div id="link_line">
	            <a href="http://css.rutgers.edu/">CSS Home</a> || <a href="http://www.rutgers.edu/">Rutgers Home</a> || <a href="http://search.rutgers.edu/">Search</a>
	        </div>
	        <div id="menu">Welcome to Rutgers Payroll, provided by Open Systems Solutions</div>
	    </div>
		<div id="main">  
		
